### ISSUE TITLE
Displaying types without reducing globally defined variables

### ISSUE THREAD

**Issue by atennapel** [AndrasKovacs/elaboration-zoo#12]
Currently if I defined a church encoded lists like:
`List t = (r : *) -> r -> (t -> r -> r) -> r`
And I defined `Nil`:
`Nil = \t n c. n : (t : *) -> List t`
The type `Nil` will get is the fully evaluated normal form of `List`.
It would be nicer if the type the user saw would be just `List t`.
I think that maybe "glued" evaluation could help, evaluating a term to two values: the normal form and the form where globally defined variables are not reduced.
But how would this go in the case of unification, where we do have to go under binders?
Do you have some ideas/pointers on this?

**Comment by AndrasKovacs** [comment]
Glued evaluation is the solution indeed.

> But how would this go in the case of unification, where we do have to go under binders?
> Do you have some ideas/pointers on this?

See [smalltt](https://github.com/AndrasKovacs/smalltt/tree/master/src). It has glued evaluation for top-level definitions.

In short, we have glued values and "local" values. Local values don't unfold top definitions and metas. [Glued values](https://github.com/AndrasKovacs/smalltt/blob/master/src/Values.hs#L57) unfold everything, but they also carry around local values, e.g. in neutral spines. We similarly duplicate the value environment in elaboration, so we have an env of glued values and another for local ones.

The simplest implementation of unification only works on glued values, we don't unify local values at all. In that case, when we do unification, we always have a glued and a local version of the two sides. We only check conversion of glued values, but when we want to solve a meta, we use the local value as meta solution. 

[Here](https://github.com/AndrasKovacs/smalltt/blob/master/src/Elaboration.hs#L334) you can see that I have a glued a local thing on both sides. Unfortunately the code here is not generally minimal, because I also implemented additional optimizations, e.g. that I first try to unify local values, and only if that fails do I try to unify glued values.
