### ISSUE TITLE
Eta reduction in evaluation

### ISSUE THREAD

**Issue by atennapel** [AndrasKovacs/elaboration-zoo#13]
Currently eta equivalence is checking during conversion checking. Eta reduction is not done during evaluation, which means the normalize function does not give an eta normal form. What's the reasoning behind not doing eta reduction during evaluation (it seems to be possible), but doing it only during conversion checking?

EDIT: I just realized that you cannot do eta reduction during evaluation because the evaluation of the body of a lambda is delayed. You could do it during quoting, but then you still have to do it during conversion checking. Basically my question is answered :).

**Comment by AndrasKovacs** [comment]
You're correct. But, to summarize what I think the main reason is for only have eta in conversion checking:

- eta reduction is inherently slow, because we have to check that vars don't occur in lambda bodies
- eta expansion can be efficient, but it requires carrying types around in evaluation (i.e. we have to know that some neutral terms has a function type to expand it)
- It is generally slower to check eta conversion by quoting to eta normal form, than to simply do conversion checking on values without quoting

Hence, IMO the simplest and fastest is to do eta conversion check on values, and don't do eta expansion/reduction in quoting.
