### ISSUE TITLE
Making lambda the only binder

### ISSUE THREAD

**Issue by atennapel** [AndrasKovacs/elaboration-zoo#22]
One way to implement dependent type theory is to have lambda be the only binder. Pi then becomes a constructor: `Pi T B` with `T : *` and `B : T -> *`. I imagine this simplifies some things, for example renaming only has to be done for lambdas. Is this a totally valid way to implement DTT or are there practical or theoretical limitations with this approach, that you know of?

**Comment by AndrasKovacs** [comment]
It's valid. There's a slight circularity if we want to formalize this syntax, there we need non-dependent functions before we can define Pi. But in implementation this doesn't matter. The main drawback is that it's less efficient, as we have to store and get through an additional lambda for each `Pi/Sigma` type. 

In cubical type theories sometimes we really want a binder abstraction instead of a lambda, and we may not even have the right function type for putting things in.

**Comment by AndrasKovacs** [comment]
Also, if you only want to abstract out renamings or other operations on binders, it's possible without lambdas; you can create something like 

    data Bind a = Bind Name Ty a

and then do

    data Tm = ... | Pi {-# unpack #-} !(Bind Ty)
                   | Lam {-# unpack #-} !(Bind Tm)
