### ISSUE TITLE
Why do we ignore the type while checking a hole?

### ISSUE THREAD

**Issue by Hirrolot** [AndrasKovacs/elaboration-zoo#38]
In `03-holes/Main.hs`, inside the function `check`, I see the following lines of code:

```haskell
  (RHole, a) ->
    freshMeta cxt
```

Why is it safe to ignore the type `a`? What if the fresh meta ends up having a type different from `a`?

**Comment by AndrasKovacs** [comment]
Nothing during elaboration can change the type of a meta. When we return the fresh meta from a hole, the type is fixed and will never change. If the meta is solved, the type of the solution is guaranteed to be the same as the type of the meta, because unification is only called when types of sides are known to be the same.

**Comment by Hirrolot** [comment]
But how do we guarantee that the fresh meta has the type `a` specifically, once it's solved?

**Comment by AndrasKovacs** [comment]
Checking returns a term which has the checking type. Evaluation preserves types. Unification is only called with values of the same type. Therefore a meta that is checked with a type can only be solved with a value with the same type.

**Comment by Hirrolot** [comment]
Thanks. So in essence, after checking any term `t` against some type `a`, we're dealing with `t` as if it's (statically) typed with `a`; and since we always unify values of the same type (which is just an implementation invariant), a freshly generated meta checked against `a` can only be unified with some value of the very same type `a`. The meta preserves its type later on because metas cannot be altered.
